kind: pipeline
type: docker
name: publish

platform:
  os: linux
  arch: arm64

steps:
  - name: npm
    image: node:latest
    environment:
      NPM_USER:
        from_secret: NPM_USERNAME
      NPM_PASS:
        from_secret: NPM_PASSWORD
      NPM_EMAIL: ari@aricodes.net
    commands:
      - npm install -g npm-login-noninteractive
      - npm-login-noninteractive
      - npm install
      - npm publish
